name: CI
on: [push, pull_request]
defaults:
  run:
    shell: pwsh
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      # MSSQL_AGENT_ENABLED: True
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
      SA_PASSWORD: ${{secrets.SAPASSWORD}}
      TEST_SQLINSTANCE: localhost
    steps:
    - uses: actions/checkout@v2

      #########
      # It might be better to do this in build.ps1
    - name:  Setup docker container
      run: |
        # create a shared volume
        docker volume create shared
        #
        # setup container and expose port
        Write-Host "INFO:Start the mssql container"
        # Do I even need persistent storage? Kind of thinking about the future, when I might need to restore a .bak or .dacpac
        docker run -p 1433:1433 -e ACCEPT_EULA -e SA_PASSWORD -e MSSQL_PID --hostname dockersql2017 --name dockersql2017 --mount 'source=shared,target=/shared' -d mcr.microsoft.com/mssql/server:2017-latest
        #
        # I am guessing that we need this sleep here. Otherwise, we tend to get those 'handshake' errors when connecting
        sleep 5
        #

      #########
    - name: Run build.ps1 / Test
      # I am unsure if I 100% understand how this works, it was set up by Plaster
      shell: pwsh
      run: ./build.ps1 -Task Test -Bootstrap

