# LINK
# https://www.robstr.dev/publish-powershellgallery-automatic-github-actions/
name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Publishing
        run: |
          # I'm sure the path is wrong, but I can't find enough info the the logs to find it.
          write-host 'where am I'
          Get-Location
          write-host 'where is the psd1 file?'
          Get-ChildItem -filter *.psd1 -Recurse -path '/home/runner/work'
          # write-host 'where is it #2'
          # Get-ChildItem -filter * -Recurse -path '/home/runner/work/ScienceOven/ScienceOven'
          write-host 'Publish'
          # Publish-Module -Path '.\ScienceOven\ScienceOven.psd1' -NuGetApiKey ${{ secrets.PSGALLERY }}
          # Working directory is: /home/runner/work/ScienceOven/ScienceOven'
          Publish-Module -Path '/home/runner/work/ScienceOven/ScienceOven/ScienceOven.psd1' -NuGetApiKey ${{ secrets.PSGALLERY }} -verbose
        shell: pwsh
