# LINK
# https://www.robstr.dev/publish-powershellgallery-automatic-github-actions/
name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Publishing
        run: |
          Publish-Module -Path '...' -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh
