# LINK
# https://www.robstr.dev/publish-powershellgallery-automatic-github-actions/
name: PSGallery
on:
  release:
    types: [published]
jobs:
  psgallery_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Publishing
        run: |
          # I'm unsure if the path is correct.
          write-host 'where am I'
          Get-Location
          write-host 'where is it'
          Get-ChildItem -filter ScienceOven.psd1 -Recurse
          write-host 'Publish'
          # Publish-Module -Path '.\ScienceOven\ScienceOven.psd1' -NuGetApiKey ${{ secrets.PSGALLERY }}
          # Workin directory is: /home/runner/work/ScienceOven/ScienceOven'
          Publish-Module -Path '.\ScienceOven\ScienceOven.psd1' -NuGetApiKey ${{ secrets.PSGALLERY }}
        shell: pwsh
